### PR TITLE
Starting to extract boilerplate into module

### PR DESCRIPTION
**Pull request by dfm**

### CODE REVIEW

**Comment by dfm** [comment]
GH Actions is down so the tests are failing: https://www.githubstatus.com/

But this is a start at some of the things in #45 

@avivajpeyi take a look and feel free to push to this branch!

**Comment by avivajpeyi** [comment]
I really like this idea! The notebook is indeed getting a bit unwieldy :) 

It all looks good to me: the only change I will make is to remove the `test_slow_notebook_execution` from the CI (its running full PE on 2 transits lol)

**Comment by dfm** [comment]
Sounds good! I've removed that test from CI. I think we're set to merge this now and start working from this?

**Comment by dfm** [comment]
Closes #47 
Closes #48

**Pull request merged**
