### PR TITLE
add ability to process single transits

### LINKED ISSUE #29: Single Transits
There might be a way to deal with single transits now! 
`assert np.all(periods > 0), "We haven't implemented single transits yet"`

### PR DESCRIPTION
**Pull request by avivajpeyi**
Closes #29 
Ref #45

### CODE REVIEW

**Comment by avivajpeyi** [comment]
###  Testing with TOI 2180



TOI | 2180.01
-- | --
Period (days)| 0.000000
epoch (TBJD)| 1830.790000
Depth (ppt)| 2.400000
Duration (days)| 1.308917





#### Lightcurve Plot
|  Data |  Zoom-in |
|---|---|
|  Screen Shot 2020-11-10 at 1 25 49 pm |  Screen Shot 2020-11-10 at 1 26 20 pm |


#### Notebook fails at:
```python
planet_transit_model, params, gp = build_planet_transit_model(tic_entry)
test_model(planet_transit_model)
```
<details>
  <summary>test_model: AssertionError due to `p=NaN` : </summary>


```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-8-8b33204d7e75> in <module>
      1 planet_transit_model, params, gp = build_planet_transit_model(tic_entry)
----> 2 test_model(planet_transit_model)

<ipython-input-7-dc9b5bb1727d> in test_model(model)
     68         test_prob = model.check_test_point()
     69         test_prob.name = "log P(test-point)"
---> 70         assert not test_prob.isnull().values.any(), test_prob
     71         test_pt = pd.Series(
     72             {

AssertionError: t0                      -0.92
p_log__                   NaN
d_log__                 -3.22
r_log__                 -0.92
b_impact__              -1.39
f0                      -3.22
u_quadlimbdark__        -2.77
jitter_log__             0.11
sigma_log__              0.11
rho_log__               -0.55
obs                -302127.33
Name: log P(test-point), dtype: float64

```

</details>

This occurs because the following array has nans:
```python
periods = np.array([planet.period for planet in tic_entry.candidates])
```


#### Next Steps:
1. When making TIC object, need to check if `PlanetCandidate` has only a `single_transit` or multiple 
2. If `candidate.single_transit == True`, we dont have a period guess, so we'll need to make a guess

Hopefully, this is all we need to do, and things might work! 

Some helpful lines from  [`tess_world`]:
```python
x = np.ascontiguousarray(lc.time, dtype=np.float64)
# ... 
single_transit = (period_guess <= 0.0) | np.isnan(period_guess)
multi_transit = ~single_transit
period_guess[single_transit] = x.max() - x.min()
period_min = np.maximum(np.abs(t0_guess - x.max()), np.abs(x.min() - t0_guess))
```



#### Note: in [`tess_world`] single_transits were treated very differently: 

There was a re-parameterization of the time parameters:
> We also fit for either :
>
> * `period`: the orbital period with a power-law prior **if single transit**, or
> * `t_max`: the time of the last transit observed by TESS, from which we can compute the period.
 
This `t_max` was used because:
> The final bit of reparameterization that we'll do is to compute the time of the *last* transit that is observed in the baseline.
> Unless we only have a single transit, we fit for this and $t_0$ instead of $t_0$ and period directly because it's easier to constrain the ranges of these parameters.
> Here we compute the time of the last transit and the number of periods between $t_0$ and "$t_\mathrm{max}$":


[`tess_world`]: https://github.com/exoplanet-dev/tess.world/blob/main/src/tess_world/templates/template.py#L305

**Comment by avivajpeyi** [comment]
Made the changes suggested above and rerunning `TOI 2180`. The initial guess doesn't look great, but hopefully our PE will solve that! 

TOI | 2180.01
-- | --
Period (days) | 351.780379
epoch (TBJD) | 1830.790000
Depth (ppt) | 2.400000
Duration (days) | 1.308917
Light curve | Screen Shot 2020-11-10 at 2 15 01 pm

**Comment by avivajpeyi** [comment]
Yikes! Sampling will take wayyy to long... hmm 

```
Sequential sampling (2 chains in 1 job)
INFO:pymc3:Sequential sampling (2 chains in 1 job)
NUTS: [rho, sigma, jitter, u, f0, b, r, d, p, t0]
INFO:pymc3:NUTS: [rho, sigma, jitter, u, f0, b, r, d, p, t0]
 3.75% [150/4000 19:04<8:09:29 Sampling chain 0, 0 divergences]
```

**Comment by avivajpeyi** [comment]
Hey @dfm , do you think this could be fine? Or that this def shouldn't take so long to run?

**Comment by dfm** [comment]
This definitely shouldn't take so long! I'll try to look into it ASAP

**Comment by dfm** [comment]
Also there's a problem if we're getting that many divergences. 1 or 2 would be fine, but not hundreds of thousands!

**Comment by avivajpeyi** [comment]
The high number of div --> degeneracy

**Comment by avivajpeyi** [comment]
Need to check -- _i think_ this might be resolved with #76

**Comment by avivajpeyi** [comment]
this has gone stale!

**Pull request closed without merging**
